### ISSUE TITLE
Document usage of onDidChangeKeyboardLayout function

### ISSUE THREAD

**Issue by spoenemann** [microsoft/node-native-keymap#10]
Tested on Mac OS 10.14.3 and Windows 10 Build 17134 with NodeJS v8.13.0 and v10.11.0

I try to register a callback function with `keymap.onDidChangeKeyboardLayout`, but that function is never called.

Here's my test repository:
https://github.com/spoenemann/native-keymap-test

Am I missing something?

**Comment by alexandrudima** [comment]
I have only tested this in Electron, and in the main process of Electron. I am not sure if it works in vanilla `node`, as that is a console application and perhaps does not receive the same events from the OS as a GUI application.

**Comment by spoenemann** [comment]
I can confirm it works in the Electron main process. This should be documented.

**Comment by alexandrudima** [comment]
:+1: Added section in README.md
