### ISSUE TITLE
Unable to install on Apple m1

### ISSUE THREAD

**Issue by luckygcb** [microsoft/node-native-keymap#35]
os version: 11.5.1
has already install libX11
![image](https://user-images.githubusercontent.com/21983011/150903221-ba80e55e-9b42-422d-aa8e-0d590ac67de3.png)

**Comment by luckygcb** [comment]
update os version to 12 is used for me

**Comment by alexdima** [comment]
@luckygcb Thanks for following through. I will close this for now.
