### ISSUE TITLE
Adds dead character into keyboard buffer for Czech Programmers layout

### ISSUE THREAD

**Issue by the-ress** [Microsoft/node-native-keymap#4]
The code adds [double acute accent](https://en.wikipedia.org/wiki/Double_acute_accent) dead character when run with Czech Programmers keyboard layout.

How to reproduce:

1. Switch to Czech Programmers layout.
2. Run `npm test`.
3. Switch to any other application.
4. Type `a`.

Result: `˝a` gets typed.

This is very annoying as it happens every time I run VS Code.

**Comment by the-ress** [comment]
It's caused by `ToUnicode` for `Shift+AltGr+VKEY_OEM_102`. It inserts the dead character into the keyboard buffer as described in [ToUnicodeEx documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646322(v=vs.85).aspx): 
> As ToUnicodeEx translates the virtual-key code, it also changes the state of the kernel-mode keyboard buffer. This state-change affects dead keys, ligatures, alt+numpad key entry, and so on.

**Comment by alexandrudima** [comment]
Fixed by PR #5
